### ISSUE TITLE
Update fast_jsonapi dependency

### ISSUE THREAD

**Issue by EmCousin** [EmCousin/grape-jsonapi#16]
Following https://github.com/Netflix/fast_jsonapi/issues/433, it appears that Netflix is no longer maintaining [fast_jsonapi](https://github.com/fast-jsonapi/fast_jsonapi). A [fork has been initiated](https://github.com/fast-jsonapi/fast_jsonapi) and seems to be well maintained and up-to-date.

Let's update the `fast_jsonapi` dependency of this gem so that it points to this fork, and ensure nothing is broken in the process.

**Comment by goalaleo** [comment]
@EmCousin any news on this switch?

**Comment by EmCousin** [comment]
@goalaleo Didn't have much time to take care of it these last few months. Pandemic and all that. I'll see if I can start something this week, but feel free to provide a PR if you already have something

**Comment by vesan** [comment]
@EmCousin The fork seems to be the new official choice. Is there something stopping from changing this gem to use [it](https://github.com/jsonapi-serializer/jsonapi-serializer)?

**Comment by EmCousin** [comment]
@vesan I [pushed a PR](https://github.com/EmCousin/grape-jsonapi/pull/23), I still need to make the build pass.
Feel free to give it a review if you have time, I would appreciate it. Thanks!

**Comment by EmCousin** [comment]
This PR is now merged into master and the gem has been renamed to `grape-jsonapi`.
It is published to [RubyGems](https://rubygems.org/gems/grape-jsonapi) here and Github Packages https://github.com/EmCousin/grape-jsonapi/packages/520462

**Comment by vesan** [comment]
Thanks a ton! Check the PR now and looked good 👍
